import { mockRoblox } from './roblox-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';

const base = process.env.TEST_BASE_URL; const db = process.env.TEST_DATABASE_URL;
test('HTTP authorization, CSRF, reauthentication and response redaction', { skip: !base || !db }, async () => {
  const endpoint = new URL(base); const database = new URL(db);
  assert.ok(['127.0.0.1', 'localhost'].includes(endpoint.hostname));
  assert.ok(['127.0.0.1', 'localhost'].includes(database.hostname) && /^\/cloudy_test_[a-z0-9_]+$/.test(database.pathname));
  process.env.DATABASE_URL = db; process.env.ENCRYPTION_KEY = 'test-key'; process.env.ROBLOX_CHECKOUT_ENABLED = 'true';
  delete process.env.TELEGRAM_BOT_TOKEN;
  const restoreRoblox = mockRoblox();
  const { prisma } = await import('../src/lib/prisma.ts');
  const { createCheckout } = await import('../src/lib/checkout.ts');
  const { applyPaymentStatus } = await import('../src/lib/payments.ts');
  try {
    const p = await prisma.product.create({ data: { name: 'HTTP Roblox', slug: `http-${crypto.randomUUID()}`, price: 0, type: 'ROBLOX', variants: { create: { name: 'Login 100', price: 2000, units: 100, method: 'LOGIN', active: true } } }, include: { variants: true } });
    const secret = { password: 'HTTP-private-password', backupCodes: ['code111','code222','code333','code444','code555'], note: 'HTTP confidential note' };
    const { order } = await createCheckout({ productId: p.id, variantId: p.variants[0].id, customerEmail: 'http@example.test', details: { username: 'httptest' } }, crypto.randomUUID());
    await applyPaymentStatus(order.id, { order_id: order.invoice, status_code: '200', transaction_status: 'settlement', gross_amount: String(order.totalAmount), currency: 'IDR' });
    const request = (path, init = {}) => fetch(new URL(path, base), init);
    // The HTTP harness mocks Roblox and blocks external providers.
    const userLookup = await request('/api/roblox/user?username=customer');
    assert.equal(userLookup.status, 200); assert.equal((await userLookup.json()).data.id, 42);
    assert.equal((await request('/api/roblox/user?username=unknown_user')).status, 404);
    assert.equal((await request('/api/roblox/user?username=%3Cinvalid%3E')).status, 400);
    assert.equal((await request('/api/roblox/gamepass?id=9999999999999999999')).status, 400);
    const passLookup = await request('/api/roblox/gamepass?id=123');
    assert.equal(passLookup.status, 200); assert.ok(passLookup.headers.get('cache-control').includes('no-store'));
    assert.equal((await passLookup.json()).data.price, 143);
    const catalogPage = await request('/roblox');
    assert.equal(catalogPage.status, 200); assert.ok((await catalogPage.text()).includes('Pilih cara kamu mendapatkan Robux'));
    const methodPage = await request(`/roblox/${p.slug}?method=LOGIN`);
    assert.equal(methodPage.status, 200); assert.ok((await methodPage.text()).includes('id="roblox-method-LOGIN"'));
    assert.equal((await request('/api/admin/fulfillment')).status, 401);
    assert.equal((await request(`/api/orders/${order.invoice}`, { headers: { 'x-order-token': 'wrong' } })).status, 404);
    const customer = await request(`/api/orders/${order.invoice}`, { headers: { 'x-order-token': order.accessToken } });
    assert.equal(customer.status, 200); assert.ok(customer.headers.get('cache-control').includes('no-store'));
    const text = await customer.text(); assert.ok(!text.includes(secret.password)); assert.ok(!text.includes('ciphertext')); assert.ok(!text.includes(secret.note)); assert.ok(!text.includes(secret.backupCodes[0]));
    const login = await request('/api/admin/auth', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: endpoint.origin }, body: JSON.stringify({ password: 'isolated-http-test-password' }) });
    assert.equal(login.status, 200);
    const cookie = login.headers.getSetCookie().find(c => c.startsWith('admin_session_token=')).split(';')[0];
    const headers = { Cookie: cookie, Origin: endpoint.origin, 'Content-Type': 'application/json' };
    const createRate = body => request('/api/admin/catalog', { method: 'POST', headers, body: JSON.stringify({ kind: 'variant', productId: p.id, name: 'Slider rate', price: 7000, units: 50, maxUnits: 5000, unitStep: 5, method: 'GAMEPASS', active: true, ...body }) });
    assert.equal((await createRate({ unitStep: 3 })).status, 400);
    assert.equal((await createRate({ maxUnits: 49 })).status, 400);
    const rateResponse = await createRate({}); assert.equal(rateResponse.status, 200);
    const rate = (await rateResponse.json()).data;
    assert.equal(rate.maxUnits, 5000); assert.equal(rate.unitStep, 5); assert.equal(rate.gamepassPrice, 72);
    const catalog = await request(`/api/products?type=ROBLOX&slug=${p.slug}`);
    const publicRate = (await catalog.json()).data[0].variants.find(v => v.id === rate.id);
    assert.equal(publicRate.maxUnits, 5000); assert.equal(publicRate.unitStep, 5);
    const giftResponse = await createRate({ name: 'Username dynamic', method: 'GIFT_USERNAME', units: 20, price: 3501, maxUnits: 200, unitStep: 2, capacityConfirmed: true });
    assert.equal(giftResponse.status, 200); const gift = (await giftResponse.json()).data;
    assert.equal(gift.maxUnits, 200); assert.equal(gift.unitStep, 2); assert.equal(gift.gamepassPrice, null);
    assert.equal((await createRate({ method: 'GIFT_USERNAME', capacityConfirmed: true, unitStep: 0 })).status, 400);
    assert.equal((await createRate({ method: 'GIFT_USERNAME', capacityConfirmed: false })).status, 400);
    const usernamePayload = { productId: p.id, variantId: gift.id, quantity: 22, customerEmail: 'username-http@example.test', details: { username: 'customer' } };
    const usernameKey = crypto.randomUUID();
    const postUsername = () => request('/api/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json', 'idempotency-key': usernameKey }, body: JSON.stringify(usernamePayload) });
    const createdUsername = await postUsername(); assert.equal(createdUsername.status, 202);
    const usernameInvoice = (await createdUsername.json()).data;
    const retriedUsername = await postUsername(); assert.equal((await retriedUsername.json()).data.invoice, usernameInvoice.invoice);
    const usernameOrder = await prisma.order.findUnique({ where: { invoice: usernameInvoice.invoice } });
    assert.equal(usernameOrder.totalAmount, 3852); assert.equal(usernameOrder.units, 22);
    const usernameCustomer = await request('/api/orders/' + usernameInvoice.invoice, { headers: { 'x-order-token': usernameInvoice.accessToken } });
    const usernameCustomerBody = await usernameCustomer.json();
    assert.equal(usernameCustomerBody.data.robloxDetail.method, 'GIFT_USERNAME');
    assert.equal(usernameCustomerBody.data.fulfillmentStatus, 'NOT_READY');
    const contactBefore = await request('/api/admin/fulfillment?q=' + order.invoice, { headers });
    assert.equal((await contactBefore.json()).data[0].contactEmail, null);
    const action = body => request(`/api/admin/fulfillment/${order.id}`, { method: 'POST', headers, body: JSON.stringify(body) });
    const csrf = await request(`/api/admin/fulfillment/${order.id}`, { method: 'POST', headers: { ...headers, Origin: 'https://evil.example' }, body: JSON.stringify({ action: 'claim' }) });
    assert.equal(csrf.status, 403);
    assert.equal((await action({ action: 'claim' })).status, 200);
    const beforeReauth = await action({ action: 'reveal' }); assert.equal(beforeReauth.status, 410); assert.equal((await beforeReauth.json()).errorCode, 'CREDENTIAL_ACCESS_REMOVED');
    const reauth = await request('/api/admin/reauth', { method: 'POST', headers, body: JSON.stringify({ password: 'isolated-http-test-password' }) }); assert.equal(reauth.status, 200);
    const reveal = await action({ action: 'reveal' }); assert.equal(reveal.status, 410); assert.ok(reveal.headers.get('cache-control').includes('no-store')); assert.equal((await reveal.json()).errorCode, 'CREDENTIAL_ACCESS_REMOVED');
    const list = await request('/api/admin/fulfillment', { headers }); const listed = await list.text(); assert.ok(!listed.includes(secret.password)); assert.ok(!listed.includes('ciphertext')); assert.ok(!listed.includes(secret.note)); assert.ok(!listed.includes(secret.backupCodes[0]));
    for (const q of [order.invoice, 'httptest', 'http@example.test']) {
      const response = await request('/api/admin/fulfillment?' + new URLSearchParams({ type: 'ROBLOX', method: 'LOGIN', payment: 'PAID', status: 'PROCESSING', q, limit: '1' }), { headers });
      assert.equal(response.status, 200); const body = await response.json();
      assert.equal(body.data[0].contactEmail, 'http@example.test'); assert.equal(body.data[0].id, order.id); assert.equal(body.data[0].robloxDetail.method, 'LOGIN');
      assert.equal(body.monitoring.pendingCount, 1);
    }
    for (const query of ['method=INVALID', 'type=APPS&method=LOGIN', 'payment=INVALID', 'q=' + 'x'.repeat(121)]) assert.equal((await request('/api/admin/fulfillment?' + query, { headers })).status, 400);
    const mismatch = await request('/api/admin/fulfillment?method=GAMEPASS&q=' + order.invoice, { headers });
    assert.equal((await mismatch.json()).data.length, 0);
    const unsafeCheckout = await request('/api/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json', 'idempotency-key': crypto.randomUUID() }, body: JSON.stringify({ productId: p.id, variantId: p.variants[0].id, customerEmail: 'http@example.test', details: { username: 'httptest', ...secret } }) });
    assert.equal(unsafeCheckout.status, 400);
    assert.equal((await action({ action: 'complete', evidence: 'http-delivery-reference' })).status, 200);
    assert.equal((await action({ action: 'reveal' })).status, 410);
    assert.equal(await prisma.orderSecret.count({ where: { orderId: order.id } }), 0);
    await request('/api/admin/auth', { method: 'DELETE', headers });
  } finally { restoreRoblox(); await prisma.$disconnect(); }
});
